### ISSUE TITLE
Dependency shading

### ISSUE THREAD

**Issue by hansenc** [datastax/pulsar-jms#14]
We need an artifact published that uses shaded dependencies to avoid classpath conflicts between the versions of  `puslar-jms` dependencies and versions that may already be in use by the client application. For reference, the official Pulsar Java client `pulsar-client-all` artifact does this ([pom.xml](https://github.com/apache/pulsar/blob/master/pulsar-client-all/pom.xml)).

Note: this would be a backward-breaking change to introduce shading to `pulsar-jms-all`, so creating a new artifact is probably the best approach.

**Comment by chrislatimer** [comment]
@nicoloboschi @eolivelli any thoughts?

**Comment by eolivelli** [comment]
working on this...stay tuned

it is also related to #16

**Comment by eolivelli** [comment]
@hansenc this is a draft PR
https://github.com/datastax/pulsar-jms/pull/17

we will cut a new release bu the end of the week

**Comment by hansenc** [comment]
Looks good pending the new release.

**Comment by hansenc** [comment]
Sorry, it looks like I was too hasty in closing. I'm seeing that the PR shaded some classes, but not all dependencies in `pulsar-jms-all`.  For example, in the 1.5.0 release, I still see `com.google.*` from Guava, which are especially problematic for this issue. Ideally, all packages other than `com.datastax.oss.pulsar.jms` should be relocated.

**Comment by eolivelli** [comment]
@hansenc I missed that you reopened this issue.

Now pulsar-jms-all behaves likes pulsar-all, and it should shade all the third party dependencies.

I have analysed the contents of pulsar-jms-all, and actually I see google packaged twice, one with a relocated package org/apache/pulsar/shade/com/google.... and one with the original one.

There should be something that didn't work correctly.

We will fix this soon

**Comment by eolivelli** [comment]
@hansenc I have sent this PR to reduce more the number of third party unshaded dependencies, especially Google stuff.
https://github.com/datastax/pulsar-jms/pull/35

I will commit as soon as CI passes

**Comment by eolivelli** [comment]
PR #35 merged.
The release will happen today or tomorrow @hansenc

**Comment by hansenc** [comment]
Much improved. Thanks.
