### ISSUE TITLE
Leverage Broker Side filtering (PIP-105) for Selectors (available from Pulsar 2.10+)

### ISSUE THREAD

**Issue by eolivelli** [datastax/pulsar-jms#18]
With PIP-105 we can implement a Filter on the Broker that allows to push the Selector into the Broker.
This way we can save network traffic, and also prevent the Consumer to receive unwanted data (that will be skipped on the client).

This is PIP-105 for reference
https://github.com/apache/pulsar/issues/12269

Some notes about a possible implementation:
- Implement the Broker side filter (it must be loaded on every Broker)
- Filtering will be done on the Broker, and this means more CPU and memory used by the Broker
- The Subscription will be tagged the JMS Selector as custom metadata (this is another feature, custom metadata for subscriptions, introduced by PIP-105)

**Comment by TianFeng111** [comment]
Can I get a release plan of Pulsar 2.10+ ? Or, maybe a stable branch which support "Broker Side filtering"?
