### ISSUE TITLE
javax.jms.IllegalStateException: This ConnectionFactory is closed after closing JNDI Context

### ISSUE THREAD

**Issue by hansenc** [datastax/pulsar-jms#20]
Closing `com.datastax.oss.pulsar.jms.jndi.PulsarContext` also closes the underlying `PulsarConnectionFactory`. If you attempt to use the connection factory after that point, you'll get `javax.jms.IllegalStateException: This ConnectionFactory is closed`.

Much of the JMS code I work with uses the following pattern, though I'm not sure if this is common, uncommon, desirable or undesirable:
1. Create JNDI context
2. Look up `ConnectionFactory`
3. Close JNDI context
4. Use  `ConnectionFactory` to create a `Connection`, etc.

The case for not closing the connection factory when the context is closed is that you don't know who has a reference to it and might still try to use it. It seems to me that JNDI / JMS implementations generally speaking do not require any explicit closing of the `ConnectionFactory`. Even if this remains required, it doesn't seem to me that closing the JNDI context is the appropriate timing for this, though I am not sure of an alternate approach so maybe that's the best that can be offered.

**Comment by eolivelli** [comment]
We can add a configuration flag to not close the Factory

**Comment by eolivelli** [comment]
in 1.5.0 we are going to deliver these changes:
- add a new configuration flag "autoCloseConnectionFactory" to control this behaviour
- by default "not closing" the ConnectionFactory (so set autoCloseConnectionFactory to false)

as it is a breaking change the release will be 1.5.0 and not 1.4.1

**Comment by eolivelli** [comment]
@hansenc @yabinmeng 
Starlight for JMS 1.5.0 has been released.

It will be available on Maven central soon (sometimes it takes a couple of hours to pop up on the repository)

The new behaviour is enabled by default (do not close the ConnectionFactory while closing the JNDI context)
