### ISSUE TITLE
Server side filtering: possible enhancements

### ISSUE THREAD

**Issue by eolivelli** [datastax/pulsar-jms#33]
I have done a few profiling sessions on server side filtering, with huge filters.

Some notes (see the image below, full flamegraph attached):
- the filter is running in the main Consumer dispatcher thread (as expected), this may affect negatively the overall performances of the broker, it the time spent in the filter is non negligible: it is not possible to move the filter to another thread, because of how the Dispatcher works (it must guarantee ordering and things like that...)
- ActiveMQ stacktrace is huge while dealing with long OR or AND expressions, because the Abstract Syntax Tree contains one node per each condition in the OR (and AND) nodes, so this is requiring many nested calls: we should create only one Node per each OR/AND conjunction in order to be able to loop over the conditions at the same level
- ActiveMQ class model is based on anonymous inner classes, and it is basically impossible to "fix" the AST and optimise the expression: we have to copy paste ActiveMQ classes or build a new library for the AST (the best would be to contribute our enhancements to ActiveMQ project)

Sample filter:
` messageSelector: (foo IN ('RO','RS','RU','SE','SI','SK','SL','SM','GI','GL','GQ','GR','HR','HU','IE','IL','IS','IT','LI','LT','LU','LV','BY','CF','CH','CS','CY','CZ','DE','DK','EE','ES','FI','FO','FR','GB','GE','MC','TJ','TR','UA','VA','AD','AL','AM','AT','AZ','BA','BE','BG','MD','ME','MK','MT','NL','NO','PL','PS','PT') OR foo IN ('RO','RS','RU','SE','SI','SK','SL','SM','GI','GL','GQ','GR','HR','HU','IE','IL','IS','IT','LI','LT','LU','LV','BY','CF','CH','CS','CY','CZ','DE','DK','EE','ES','FI','FO','FR','GB','GE','MC','TJ','TR','UA','VA','AD','AL','AM','AT','AZ','BA','BE','BG','MD','ME','MK','MT','NL','NO','PL','PS','PT') OR (foo IN ('AU','NZ')) OR (foo IN ('AZ','CY','GH','GI','IS','KE','LB','LR','NG','RW','TZ','ZA','ZM','GE','QA','ZW')) OR (foo IN ('AZ','CY','GH','GI','IS','KE','LB','LR','NG','RW','TZ','ZA','ZM')) OR (foo='US' AND foo='EG') OR (foo='KR' AND foo='QA') OR (foo='US' AND foo='ZA') OR (foo='NZ' AND foo='ZA') OR (foo='CA' AND foo='EG') OR foo IN ('AG','AI','AO','AW','BB','BD','BF','BI','BM','BN','BO','BQ','BS','BW','BZ','CD','CI','CL','CM','CR','CV','CW','DJ','DM','EG','ET','FJ','GD','GH','GN','GP','GT','GU','GY','HN','HT','JM','KE','KG','KH','KN','KY','KZ','LB','LC','LK','MA','MG','MO','MP','MQ','MR','MU','MW','MZ','NA','NC','NG','NI','NP','OM','PA','PE','PF','PG','RW','SA','SC','SN','SR','SV','SX','SZ','TC','TG','TN','TO','TT','TZ','UY','UZ','VC','VE','VG','VI','ZA','ZM','ZW','AD','AL','AM','AT','AZ','BA','BE','BG','BY','CF','CH','CS','CY','CZ','DE','DK','EE','ES','FI','FO','FR','GB','GE','GI','GL','GQ','GR','HR','HU','IE','IL','IS','IT','LI','LR','LT','LU','LV','MC','MD','ME','MK','MT','NL','NO','PL','PS','PT','RO','RS','RU','SE','SI','SK','SL','SM','TJ','TR','UA','VA') OR foo IN ('AE','AD','AF','AG','AI','AL','AM','AO','AR','AS','AT','AU','AW','AZ','BA','BB','BD','BE','BF','BG','BH','BI','BJ','BM','BN','BO','BQ','BR','BS','BT','BW','BY','BZ','CD','CF','CG','CH','CI','CK','CL','CM','CO','CR','CS','CV','CW','CY','CZ','DE','DJ','DK','DM','DO','DZ','EC','EE','EG','ER','ES','ET','FI','FJ','FM','FO','FR','GA','GB','GD','GE','GF','GH','GI','GL','GM','GN','GP','GQ','GR','GT','GU','GY','HN','HR','HT','HU','ID','IE','IL','IN','IQ','IS','IT','JM','JO','KE','KG','KH','KN','KW','KY','KZ','LA','LB','LC','LI','LK','LR','LS','LT','LU','LV','LY','MA','MC','MD','ME','MG','MH','MK','ML','MM','MN','MO','MP','MQ','MR','MS','MT','MU','MV','MW','MZ','NA','NC','NE','NG','NI','NL','NO','NP','NZ','OM','PA','PE','PF','PG','PH','PK','PL','PS','PT','PW','PY','QA','RE','RO','RS','RU','RW','SA','SB','SC','SE','SI','SK','SL','SM','SN','SR','SV','SX','SZ','TC','TD','TG','TJ','TL','TN','TO','TR','TT','TZ','UA','UG','UY','UZ','VA','VC','VG','VI','VN','VU','WF','WS','ZA','ZM','ZW') OR (foo='BH' AND foo='US') OR (foo='CA' AND foo='CN') OR (foo='CA' AND foo='JP') OR (foo='CN' AND foo='CA') OR (foo='CN' AND foo='US') OR (foo='DZ' AND foo='CN') OR (foo='IN' AND foo='CA') OR (foo='IN' AND foo='CA') OR (foo='IN' AND foo='CN') OR (foo='IN' AND foo='HK') OR (foo='IN' AND foo='JP') OR (foo='IN' AND foo='KR') OR (foo='IN' AND foo='MX') OR (foo='IN' AND foo='MY') OR (foo='IN' AND foo='SG') OR (foo='IN' AND foo='TH') OR (foo='IN' AND foo='TW') OR (foo='IN' AND foo='US') OR (foo='IQ' AND foo='US') OR (foo='JO' AND foo='US') OR (foo='JP' AND foo='US') OR (foo='KW' AND foo='CA') OR (foo='KW' AND foo='US') OR (foo='MX' AND foo='HK') OR (foo='QA' AND foo='US') OR (foo='UG' AND foo='US') OR (foo='US' AND foo='CN') OR (foo='US' AND foo='HK') OR (foo='US' AND foo='JP') OR (foo='US' AND foo='SG') OR (foo='US' AND foo='TH') OR (foo='US' AND foo='TW') OR (foo='US' AND foo='VE')) or foo = 'bar'`

![image](https://user-images.githubusercontent.com/9469110/170496564-7b156e07-0d87-4158-8f49-9b3cb4501bfa.png)

**Comment by eolivelli** [comment]
Full flamegraph here: [profile.html.tar.gz](https://github.com/datastax/pulsar-jms/files/8779326/profile.html.tar.gz)

**Comment by dave2wave** [comment]
Does a HashSet make sense for a contains with only a few members? Wouldn't a compiled state machine approach be better than a stack of recursion?
