### ISSUE TITLE
Cannot Call this method inside the listener

### ISSUE THREAD

**Issue by akhil1000** [datastax/pulsar-jms#63]
Hello Enrico - We are getting this exception with one of the teams here .Inside onMessage they call some service which was error-ing out with null pointer .. but after that pulsar throws this exception. "Cannot Call this method inside the listener" Screen shot attached.

2022-09-01 15:51:00,618 ERROR [agency.core.AckProcessorSingleTxController] Could not process ack
     [java] java.lang.NullPointerException
     [java] 	at com.intuit.engine.efp.efe.agency.core.AckProcessorSingleTxController.process(AckProcessorSingleTxController.java:41)
     [java] 	at com.intuit.engine.efp.efe.agency.core.AckProcessorBean.doOnMessage(AckProcessorBean.java:46)
     [java] 	at com.intuit.engine.efp.efe.mpc.messaging.efeservice.EfeServiceMdb.onMessage(EfeServiceMdb.java:156)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at org.jboss.invocation.Invocation.performCall(Invocation.java:359)
     [java] 	at org.jboss.ejb.MessageDrivenContainer$ContainerInterceptor.invoke(MessageDrivenContainer.java:492)
     [java] 	at org.jboss.resource.connectionmanager.CachedConnectionInterceptor.invoke(CachedConnectionInterceptor.java:158)
     [java] 	at org.jboss.ejb.plugins.CallValidationInterceptor.invoke(CallValidationInterceptor.java:63)
     [java] 	at org.jboss.ejb.plugins.AbstractTxInterceptor.invokeNext(AbstractTxInterceptor.java:121)
     [java] 	at org.jboss.ejb.plugins.AbstractTxInterceptorBMT.invokeNext(AbstractTxInterceptorBMT.java:173)
     [java] 	at org.jboss.ejb.plugins.MessageDrivenTxInterceptorBMT.invoke(MessageDrivenTxInterceptorBMT.java:47)
     [java] 	at org.jboss.ejb.plugins.MessageDrivenInstanceInterceptor.invoke(MessageDrivenInstanceInterceptor.java:116)
     [java] 	at org.jboss.ejb.plugins.RunAsSecurityInterceptor.invoke(RunAsSecurityInterceptor.java:109)
     [java] 	at org.jboss.ejb.plugins.LogInterceptor.invoke(LogInterceptor.java:205)
     [java] 	at org.jboss.ejb.plugins.ProxyFactoryFinderInterceptor.invoke(ProxyFactoryFinderInterceptor.java:138)
     [java] 	at org.jboss.ejb.MessageDrivenContainer.internalInvoke(MessageDrivenContainer.java:399)
     [java] 	at org.jboss.ejb.Container.invoke(Container.java:960)
     [java] 	at org.jboss.ejb.plugins.jms.JMSContainerInvoker.invoke(JMSContainerInvoker.java:1139)
     [java] 	at org.jboss.ejb.plugins.jms.JMSContainerInvoker$MessageListenerImpl.onMessage(JMSContainerInvoker.java:1452)
     [java] 	at org.jboss.jms.asf.StdServerSession.onMessage(StdServerSession.java:266)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarMessageConsumer.lambda$null$4(PulsarMessageConsumer.java:626)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarMessageConsumer.handleReceivedMessage(PulsarMessageConsumer.java:441)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarMessageConsumer.lambda$runListener$5(PulsarMessageConsumer.java:622)
     [java] 	at com.datastax.oss.pulsar.jms.Utils.lambda$executeMessageListenerInSessionContext$0(Utils.java:118)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarSession.executeCriticalOperation(PulsarSession.java:1674)
     [java] 	at com.datastax.oss.pulsar.jms.Utils.executeMessageListenerInSessionContext(Utils.java:116)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarMessageConsumer.runListener(PulsarMessageConsumer.java:608)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarSession.lambda$run$0(PulsarSession.java:677)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarConnection.executeInConnectionPausedLock(PulsarConnection.java:880)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarSession.run(PulsarSession.java:675)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarSession$ListenerThread.run(PulsarSession.java:1735)
     [java] 2022-09-01 15:51:00,686 ERROR [jms.asf.StdServerSession] failed to commit/rollback
     [java] javax.jms.IllegalStateException: Cannot call this method inside a listener
     [java] 	at com.datastax.oss.pulsar.jms.Utils.checkNotOnMessageListener(Utils.java:156)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarSession.commit(PulsarSession.java:391)
     [java] 	at org.jboss.jms.asf.StdServerSession.onMessage(StdServerSession.java:357)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarMessageConsumer.lambda$null$4(PulsarMessageConsumer.java:626)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarMessageConsumer.handleReceivedMessage(PulsarMessageConsumer.java:441)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarMessageConsumer.lambda$runListener$5(PulsarMessageConsumer.java:622)
     [java] 	at com.datastax.oss.pulsar.jms.Utils.lambda$executeMessageListenerInSessionContext$0(Utils.java:118)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarSession.executeCriticalOperation(PulsarSession.java:1674)
     [java] 	at com.datastax.oss.pulsar.jms.Utils.executeMessageListenerInSessionContext(Utils.java:116)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarMessageConsumer.runListener(PulsarMessageConsumer.java:608)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarSession.lambda$run$0(PulsarSession.java:677)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarConnection.executeInConnectionPausedLock(PulsarConnection.java:880)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarSession.run(PulsarSession.java:675)
     [java] 	at com.datastax.oss.pulsar.jms.PulsarSession$ListenerThread.run(PulsarSession.java:1735)

**Comment by eolivelli** [comment]
The trigger of the problem is that JBoss is calling "commit" on the Session inside the execution of a MessageListener


[java] 2022-09-01 15:51:00,686 ERROR [jms.asf.StdServerSession] failed to commit/rollback
[java] javax.jms.IllegalStateException: Cannot call this method inside a listener
[java] at com.datastax.oss.pulsar.jms.Utils.checkNotOnMessageListener(Utils.java:156)
[java] at com.datastax.oss.pulsar.jms.PulsarSession.commit(PulsarSession.java:391)
**[java] at org.jboss.jms.asf.StdServerSession.onMessage(StdServerSession.java:357)**


Before doing any change to the code, are you sure that this is happening **after** the `NullPointerException` ?
it may be that JBoss goes into some corrupted state and tries to recover the status of the session some how.

has it ever recovered ?

Which version of JBoss are you running ? I would like to find the source code and understand better the problem
