### ISSUE TITLE
MinSession/maxsession implementation 

### ISSUE THREAD

**Issue by akhil1000** [datastax/pulsar-jms#85]
Do we have this implemented in resource adapter ? It seems parallel threads are not consuming messages. 
Messages are consumed one at a time on one consumer.

<activation-config-property>
					<activation-config-property-name>minSession</activation-config-property-name>
					<activation-config-property-value>1</activation-config-property-value>
				</activation-config-property>
				<activation-config-property>
					<activation-config-property-name>maxSession</activation-config-property-name>
					<activation-config-property-value>10</activation-config-property-value>
				</activation-config-property>
<activation-config-property>
					<activation-config-property-name>maxMessages</activation-config-property-name>
					<activation-config-property-value>25</activation-config-property-value>
				</activation-config-property>

**Comment by eolivelli** [comment]
Can you share your ejb configuration please?

**Comment by eolivelli** [comment]
implemented
